# Generated by Django 6.0.7 on 2026-07-20 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('duree', models.IntegerField(help_text='Durée en minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id_filiere', models.AutoField(primary_key=True, serialize=False)),
                ('nom_filiere', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id_fonction', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.utilisateur',),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id_prom', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=200)),
                ('annee_academique', models.CharField(max_length=20)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('num_matric', models.CharField(max_length=50, unique=True)),
                ('date_naiss', models.DateField()),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='core.promotion')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.utilisateur',),
        ),
        migrations.CreateModel(
            name='Chrono_Horaire',
            fields=[
                ('id_chrono', models.AutoField(primary_key=True, serialize=False)),
                ('heure', models.TimeField()),
                ('jours', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PROPOSED', 'Proposé'), ('CONFIRMED', 'Confirmé'), ('PUBLISHED', 'Publié')], default='DRAFT', max_length=20)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='core.cours')),
                ('fonction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupations', to='core.fonction')),
                ('consultants', models.ManyToManyField(blank=True, related_name='horaires_consultes', to='core.etudiant')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_cours', to='core.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('id_util', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_associes', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
            options={
                'unique_together': {('id_util', 'role')},
            },
        ),
    ]
