# Generated by Django 6.0.7 on 2026-07-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_naiss',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='num_matric',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='matricule',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
