# Generated by Django 6.0.7 on 2026-07-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_etudiant_date_naiss_alter_etudiant_num_matric_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'verbose_name': 'Etudiant', 'verbose_name_plural': 'Etudiants'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': 'Personnel', 'verbose_name_plural': 'Personnels'},
        ),
        migrations.RemoveField(
            model_name='chrono_horaire',
            name='consultants',
        ),
        migrations.AddField(
            model_name='chrono_horaire',
            name='annotations',
            field=models.TextField(blank=True, help_text="Annotations ou demandes de modification de l'enseignant", null=True),
        ),
        migrations.AlterField(
            model_name='chrono_horaire',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PROPOSED', 'Proposé (Chef Filière)'), ('CONFIRMED', 'Confirmé (SGA)'), ('PUBLISHED', 'Publié')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('note', models.TextField(blank=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='core.personnel')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
            },
        ),
    ]
