# Generated by Django 5.2.16 on 2026-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_etudiant_options_alter_personnel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='duree',
            field=models.PositiveIntegerField(help_text='Durée en minutes'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='nom_filiere',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='chrono_horaire',
            constraint=models.UniqueConstraint(fields=('jours', 'heure', 'personnel'), name='unique_creneau_personnel'),
        ),
        migrations.AddConstraint(
            model_name='disponibilite',
            constraint=models.CheckConstraint(check=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='disponibilite_fin_apres_debut'),
        ),
    ]
