# Generated by Django 4.2 on 2026-07-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cours_duree_alter_filiere_nom_filiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrono_horaire',
            name='jours',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(fields=('designation', 'annee_academique', 'filiere'), name='unique_promotion_filiere_annee'),
        ),
    ]
